package com.cho_co_song_i.yummy.yummy.enums;

public enum PublicStatus {
    SUCCESS,
    NAME_ERR,
    ID_ERR,
    EMAIL_ERR,
    PW_FIND_ERR,
    PW_CHECK_ERR,
    TELECOM_ERR,
    PHONE_ERR,
    PHONE_DUPLICATED,
    ID_FIND_ERR,
    ID_DUPLICATED,
    PW_ERR,
    BIRTH_ERR,
    GENDER_ERR,
    AUTH_ERROR,
    SERVER_ERR,
    TOKEN_ERR,
    REJOIN_CHECK,
    JOIN_TARGET_MEMBER,
    CASE_ERR,
    TEMP_PW_CHECK,
    LOGIN_AGAIN,
}
